[package]
name = "rust-game-test"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.19.0"

[package.metadata.scripts]
serve = "~/.cargo/bin/trunk serve --open"
build-web = "~/.cargo/bin/trunk build --release"

[lints.clippy]
shadow_reuse = "deny"
shadow_same = "deny"
shadow_unrelated = "deny"

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3
